/* FOX OS Chromebook Companion — v0.8 Custom Workspace
   v0.7 UI retained; this file adds stronger persistence, custom pages, widgets,
   circuit persistence, autosave status, and full workspace backup/restore.
*/
let deferredInstall=null;
const A=document.getElementById("app"),T=document.getElementById("title"),toastEl=document.getElementById("toast"),saveStateEl=document.getElementById("saveState");
const STORAGE_KEY="foxos_v08";
const LEGACY_KEY="foxos_v07";
const defaults={name:"FOX OS Sandbox",owner:"Foxbin",version:"0.8.0",accent:"#0796e6",target:"BONELAB",files:{
"Main.cs":`using BoneLib;\n\nnamespace FOXOS {\n    public class Main {\n        public void Start() {\n            // FOX OS entry point\n        }\n    }\n}\n`}};
const baseState={
 project:structuredClone(defaults),view:"home",file:"Main.cs",builds:[],history:[],bookmarks:["https://github.com/foxbin8766-oss/FoxOSC"],
 settings:{accent:"#0796e6",theme:"midnight",wallpaper:"grid",density:"comfortable",scale:"100%",animations:true,sidebar:"230px",startup:"home",showBrand:true,showClock:true,autosave:true},
 memories:[],tasks:[{id:1,title:"Explore FOX OS",done:false},{id:2,title:"Connect Quest later",done:false}],
 plugins:[{id:"core",name:"FOX Core",enabled:true,source:"built-in"},{id:"bonelab",name:"BONELAB Adapter",enabled:true,source:"built-in"},{id:"writhub",name:"WristHub / BoneLib",enabled:true,source:"built-in"}],
 agents:[{id:"evan",name:"Evan",role:"Primary FOX OS co-creator",status:"Ready",enabled:true}],notifications:[],
 devices:{quest:"virtual",status:"Connected (Virtual)"},
 shortcuts:[{key:"Ctrl+K",action:"Command palette"},{key:"Ctrl+S",action:"Save workspace"},{key:"Ctrl+B",action:"Build / validate"}],
 studio:{mode:"edit",objects:["Player Spawn","Interactable Door","Vehicle","Enemy"],scene:"Forest Test Scene"},
 world:{grid:true,day:12,weather:"Clear",nodes:["Spawn","Light","Door Trigger"]},
 circuits:{nodes:[{id:"n1",kind:"Start",x:35,y:35},{id:"n2",kind:"Logic",x:240,y:145},{id:"n3",kind:"Output",x:470,y:250}],runs:0},
 pages:[],profile:{displayName:"Foxbin",subtitle:"FOX OS Creator",avatar:"fox-os-logo.png"}
};
function clone(x){return structuredClone(x)}
function migrate(raw){
  const s={...clone(baseState),...(raw||{})};
  s.project={...clone(defaults),...(raw?.project||{})};
  s.project.files={...clone(defaults.files),...(raw?.project?.files||{})};
  s.settings={...clone(baseState.settings),...(raw?.settings||{})};
  s.pages=Array.isArray(raw?.pages)?raw.pages:[];
  s.profile={...clone(baseState.profile),...(raw?.profile||{})};
  s.circuits={...clone(baseState.circuits),...(raw?.circuits||{})};
  return s;
}
function load(){
  try{
    const current=localStorage.getItem(STORAGE_KEY);
    if(current)return migrate(JSON.parse(current));
    const legacy=localStorage.getItem(LEGACY_KEY);
    if(legacy)return migrate(JSON.parse(legacy));
  }catch{}
  return clone(baseState);
}
let state=load();
let view=state.view||state.settings.startup||"home",file=state.file||Object.keys(state.project.files)[0]||"Main.cs";
let saveTimer=null,lastSavedAt=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function setSaveState(text,kind="saved"){if(!saveStateEl)return;saveStateEl.textContent=text;saveStateEl.dataset.state=kind}
function persistNow(showToast=false){
  try{
    state.view=view;state.file=file;
    localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
    lastSavedAt=new Date();
    setSaveState("Saved • "+lastSavedAt.toLocaleTimeString([], {hour:"numeric",minute:"2-digit",second:"2-digit"}),"saved");
    if(showToast)toast("Workspace saved");
    return true;
  }catch(err){setSaveState("Save failed","error");console.error(err);return false}
}
function save(opts={}){
  if(state.settings?.autosave===false){setSaveState("Autosave off","idle");return}
  setSaveState("Saving…","saving");clearTimeout(saveTimer);saveTimer=setTimeout(()=>persistNow(!!opts.toast),120);
}
function flushSave(){clearTimeout(saveTimer);persistNow(false)}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>toastEl.classList.remove("show"),2200)}
function notify(msg){state.notifications.unshift({msg,time:new Date().toLocaleTimeString()});state.notifications=state.notifications.slice(0,25);save();toast(msg)}
function go(v){flushSave();view=v;render()}
function titleForCustomPage(){const p=state.pages.find(x=>x.id===view.slice(5));return p?.title||"My Page"}
function setTitle(){const names={home:"Home",projects:"Projects",code:"Code",circuits:"Circuits",studio:"Game Studio",world:"World Builder",memory:"Memory Core",devices:"Device Bridge",permissions:"Permissions",agents:"Agents",sim:"Simulator",systems:"Systems",browser:"Browser",logs:"Build / Logs",docs:"Docs",settings:"Settings",plugins:"Plugins",tasks:"Tasks",pages:"My Pages"};T.textContent=view.startsWith("page:")?titleForCustomPage():(names[view]||"FOX OS")}
function projectCount(){return Object.keys(state.project.files).length}
function render(){
  flushSave();setTitle();
  document.documentElement.style.setProperty("--sidebar",state.settings.sidebar||"230px");
  document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.v===view));
  let h="";
  if(view==="home")h=home();else if(view==="projects")h=projects();else if(view==="code")h=code();else if(view==="circuits")h=circuits();else if(view==="studio")h=studio();else if(view==="world")h=world();else if(view==="memory")h=memory();else if(view==="devices")h=devices();else if(view==="permissions")h=permissions();else if(view==="agents")h=agents();else if(view==="sim")h=simulator();else if(view==="systems")h=systems();else if(view==="browser")h=browser();else if(view==="logs")h=logs();else if(view==="docs")h=docs();else if(view==="settings")h=settings();else if(view==="plugins")h=plugins();else if(view==="tasks")h=tasks();else if(view==="pages")h=pagesManager();else if(view.startsWith("page:"))h=customPage(view.slice(5));
  A.innerHTML=h;bind();updateDynamicNav();applyTheme();
}
function home(){
  const last=state.builds.at(-1),pending=state.tasks.filter(x=>!x.done).length,custom=state.pages.length;
  return `<div class="profile"><img class="avatar" src="${esc(state.profile.avatar||"fox-os-logo.png")}" alt="FOX OS"><div><h1>Welcome back, ${esc(state.profile.displayName||state.project.owner||"Foxbin")}</h1><p class="muted">${esc(state.profile.subtitle||"FOX OS Chromebook Developer Companion")} • v${esc(state.project.version||"0.8.0")}</p></div></div>
  <div class="grid three" style="margin-top:18px"><div class="card"><div class="stat">${projectCount()}</div><div class="statlabel">Project files</div></div><div class="card"><div class="stat">${state.builds.length}</div><div class="statlabel">Build runs</div></div><div class="card"><div class="stat">${pending}</div><div class="statlabel">Open tasks</div></div></div>
  <div class="grid" style="margin-top:12px"><div class="card"><div class="rowline"><h2>FOX Command Center</h2><span class="badge ok">${esc(state.devices.status)}</span></div><p><b>${esc(state.project.name)}</b> <span class="muted">v${esc(state.project.version)}</span></p><div class="toolbar"><button class="primary" onclick="go('studio')">Open Game Studio</button><button onclick="go('world')">Build World</button><button onclick="go('code')">Open Code</button></div></div>
  <div class="card"><h2>Quick Actions</h2><div class="toolbar"><button onclick="snapshot()">Create Snapshot</button><button onclick="build()">Validate Project</button><button onclick="exportWorkspace()">Backup Workspace</button></div><p class="muted">${last?`Last build: ${esc(last.result)} • ${esc(last.time)}`:"No builds yet."}</p></div></div>
  <div class="grid" style="margin-top:12px"><div class="card"><h2>Custom Pages</h2><p class="muted">${custom} saved page${custom===1?"":"s"}. Pages are stored in your local FOX OS workspace.</p><div class="toolbar"><button class="primary" onclick="go('pages')">Open My Pages</button><button onclick="createPage()">+ Create Page</button></div>${state.pages.slice(0,3).map(p=>`<div class="row"><span><b>${esc(p.icon||"▣")} ${esc(p.title)}</b><br><small class="muted">${esc(p.subtitle||"Custom FOX OS page")} • ${p.blocks?.length||0} blocks</small></span><button onclick="go('page:${p.id}')">Open</button></div>`).join("")||"<p class=\"muted\">Create your first page and add live widgets, notes, tasks, links, and project tools.</p>"}</div>
  <div class="card"><h2>Notifications</h2>${state.notifications.slice(0,6).map(n=>`<div class="row"><span>${esc(n.msg)}</span><span class="tiny">${esc(n.time)}</span></div>`).join("")||'<p class="muted">No notifications.</p>'}</div></div>`;
}
function projects(){return `<div class="grid"><div class="card"><h2>${esc(state.project.name)}</h2><p class="muted">Target: ${esc(state.project.target)} • ${projectCount()} files</p><div class="toolbar"><button onclick="newProject()">New</button><button onclick="importP()">Import</button><button onclick="exportP()">Export Project</button><button onclick="duplicateProject()">Duplicate</button></div></div><div class="card"><h2>Project tools</h2><button onclick="renameProject()">Rename Project</button><button onclick="addFile()">Add File</button><button onclick="snapshot()">Snapshot</button></div></div><div class="list" style="margin-top:12px">${Object.keys(state.project.files).map(f=>`<div class="row"><span><b>${esc(f)}</b><span class="muted"> • ${state.project.files[f].length} chars</span></span><button onclick="sel('${esc(f)}')">Edit</button></div>`).join("")}</div>`}
function code(){return `<div class="split"><div class="files">${Object.keys(state.project.files).map(f=>`<button class="${f===file?"active":""}" onclick="sel('${esc(f)}')">${esc(f)}</button>`).join("")}<div class="toolbar"><button onclick="addFile()">+ File</button><button onclick="deleteFile()">Delete</button></div></div><div class="editor"><small><span>${esc(file)}</span><span>FOX Code • auto-saves</span></small><textarea id="ed" spellcheck="false">${esc(state.project.files[file]||"")}</textarea><div class="toolbar"><button onclick="insertTemplate('BoneLib')">BoneLib Template</button><button onclick="insertTemplate('WristHub')">WristHub Template</button><button onclick="insertTemplate('Event')">Event Template</button><button class="primary" onclick="build()">Validate</button></div></div></div>`}
function circuits(){const nodes=state.circuits.nodes||[];return `<div class="grid"><div class="card"><h2>FOX Circuits</h2><p class="muted">Add and drag nodes. Positions and runs are saved automatically.</p><div class="toolbar"><button onclick="addChip('Event')">+ Event</button><button onclick="addChip('Logic')">+ Logic</button><button onclick="addChip('Variable')">+ Variable</button><button onclick="addChip('Action')">+ Action</button><button class="primary" onclick="runCircuit()">Run</button><button onclick="clearCircuit()">Reset Canvas</button></div></div><div class="card"><h2>Saved circuit</h2><div class="stat">${state.circuits.runs||0}</div><div class="statlabel">Runs</div><p class="muted">${nodes.length} nodes saved in your workspace.</p></div></div><div id="circuit" class="circuit" style="margin-top:12px">${nodes.map(n=>`<div class="chip" data-node="${esc(n.id)}" style="left:${n.x}px;top:${n.y}px">${esc(n.kind)}</div>`).join("")}</div>`}
function studio(){return `<div class="grid"><div class="card"><h2>FOX Game Studio</h2><p class="muted">Mode: ${esc(state.studio.mode)} • Scene: ${esc(state.studio.scene)}</p><div class="toolbar"><button class="primary" onclick="toggleStudioMode()">Toggle ${state.studio.mode==="edit"?"Play":"Edit"}</button><button onclick="addStudioObject()">Add Object</button><button onclick="clearStudio()">Clear</button><button onclick="saveStudioScene()">Save Scene</button></div>${state.studio.objects.map((o,i)=>`<div class="row"><span>${esc(o)}</span><button onclick="removeStudioObject(${i})">Remove</button></div>`).join("")}</div><div class="card"><h2>Interaction Lab</h2><p>Prototype interaction without a real game runtime: triggers, inventory/equipment, vehicles, AI entities and scene logic.</p><button onclick="notify('Interaction test started')">Test Interaction</button><button onclick="addStudioObjectNamed('Interaction Trigger')">Add Trigger</button></div></div>`}
function world(){return `<div class="grid"><div class="card"><h2>FOX World Builder</h2><div class="setting"><span>Grid</span><input id="worldGrid" type="checkbox" ${state.world.grid?"checked":""}></div><div class="setting"><span>Time of day</span><input id="worldDay" type="range" min="0" max="24" step="1" value="${state.world.day}"></div><div class="setting"><span>Weather</span><select id="worldWeather"><option ${state.world.weather==="Clear"?"selected":""}>Clear</option><option ${state.world.weather==="Rain"?"selected":""}>Rain</option><option ${state.world.weather==="Fog"?"selected":""}>Fog</option><option ${state.world.weather==="Storm"?"selected":""}>Storm</option></select></div><button class="primary" onclick="saveWorld()">Save World</button></div><div class="card"><h2>Scene Nodes</h2>${state.world.nodes.map((n,i)=>`<div class="row"><span>${esc(n)}</span><button onclick="removeWorldNode(${i})">Remove</button></div>`).join("")}<button onclick="addWorldNode()">Add Node</button></div></div>`}
function memory(){return `<div class="grid"><div class="card"><h2>FOX Memory Core</h2><p class="muted">Local project memories and snapshots. Nothing is sent anywhere by this companion.</p><input id="memText" type="text" placeholder="Remember this project detail..."><button class="primary" onclick="addMemory()">Save Memory</button><button onclick="snapshot()">Create Snapshot</button></div><div class="card"><h2>Memories</h2>${state.memories.map((m,i)=>`<div class="row"><span>${esc(m.text)}<small class="muted"> • ${esc(m.time)}</small></span><button onclick="deleteMemory(${i})">Delete</button></div>`).join("")||'<p class="muted">No memories yet.</p>'}</div></div>`}
function devices(){return `<div class="grid"><div class="card"><h2>Quest Device Bridge</h2><p>Status: <span class="badge ok">${esc(state.devices.status)}</span></p><p class="muted">This is a virtual Quest endpoint. Real Quest pairing can be enabled later without changing the project model.</p><div class="toolbar"><button onclick="pairQuest()">Pair Virtual Quest</button><button onclick="disconnectQuest()">Disconnect</button><button onclick="sendTest()">Send Test</button></div></div><div class="card"><h2>Bridge capabilities</h2><p>Project transfer • permissions • device state • future APK deployment • FOX game control</p></div></div>`}
function permissions(){return `<div class="card"><h2>Permission Center</h2>${["Project read/write","Memory access","Device pairing","Game Studio execution","Plugin management","Build/export"].map((x,i)=>`<div class="setting"><span>${x}</span><input type="checkbox" checked data-perm="${i}"></div>`).join("")}<p class="muted">Permissions are local companion controls and do not grant the app access to external devices by themselves.</p></div>`}
function agents(){return `<div class="grid"><div class="card"><h2>Agents</h2>${state.agents.map(a=>`<div class="row"><span><b>${esc(a.name)}</b><br><small class="muted">${esc(a.role)} • ${esc(a.status)}</small></span><button onclick="toggleAgent('${esc(a.id)}')">${a.enabled?"Disable":"Enable"}</button></div>`).join("")}<button onclick="addAgent()">Add Agent</button></div><div class="card"><h2>Evan</h2><p>Primary FOX OS co-creator agent. Project-aware tools can be attached here as the ecosystem grows.</p><button onclick="notify('Evan workspace opened')">Open Workspace</button></div></div>`}
function simulator(){return `<div class="sim"><div class="simbar"><b>FOX OS Virtual Device</b><span class="badge ok">${esc(state.devices.status)}</span></div><div class="apps">${["FOX Home","WristHub","BONELAB","Settings","Memory","Games"].map(x=>`<button onclick="simOpen('${esc(x)}')">${esc(x)}</button>`).join("")}</div><div id="simWindow" class="appwindow"><b>Virtual Quest ready</b><p class="muted">Select an app to preview its future in-headset interface.</p></div></div>`}
function systems(){return `<div class="card"><h2>System Registry</h2><input id="systemSearch" class="search" placeholder="Search systems..."><table><thead><tr><th>System</th><th>Status</th><th>Purpose</th></tr></thead><tbody id="systemRows">${[["FOX Core","Ready","Shared architecture"],["Memory Core","Ready","Persistent local project context"],["Device Bridge","Virtual","Quest connectivity"],["Game Studio","Prototype","Game creation"],["World Builder","Prototype","Scene creation"],["WristHub","Integrated","Watch UI"],["BoneLib","Integrated","BONELAB APIs"],["Custom Pages","Ready","User-built FOX OS pages"],["Workspace Storage","Ready","Local browser/PWA persistence"]].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join("")}</tbody></table></div>`}
function browser(){return `<div class="browser"><div class="toolbar"><button onclick="browserBack()">←</button><button onclick="browserForward()">→</button><button onclick="reload()">↻</button><input id="url" class="url" value="${esc(state.settings.lastUrl||"https://www.google.com")}"><button onclick="nav()">Go</button><button onclick="bookmark()">☆</button><button onclick="chrome()">↗</button></div><iframe id="frame" class="frame" src="${esc(state.settings.lastUrl||"https://www.google.com")}" title="FOX Browser"></iframe></div>`}
function logs(){return `<div class="card"><div class="rowline"><h2>Build / Logs</h2><button onclick="build()">Run Validation</button></div><div id="log" class="log">${state.builds.map(b=>`[${esc(b.time)}] ${esc(b.result)}`).join("\n")}</div></div>`}
function docs(){return `<div class="grid"><div class="card"><h2>FOX OS Docs</h2><p>FOX OS is a modular BONELAB code-mod ecosystem with a Chromebook companion for development and control.</p><h3>Architecture</h3><p class="muted">FOX Core → modules → project/game systems → optional device bridges. The Chromebook app is not itself the BONELAB mod.</p></div><div class="card"><h2>Developer Notes</h2><p>Use BoneLib and WristHub integrations through their supported APIs. Keep device-specific features behind the Device Bridge.</p></div></div>`}
function settings(){const s=state.settings;return `<div class="grid"><div class="card"><h2>Personalization</h2><div class="setting"><span>Display name</span><input id="profileName" type="text" value="${esc(state.profile.displayName)}"></div><div class="setting"><span>Profile subtitle</span><input id="profileSubtitle" type="text" value="${esc(state.profile.subtitle)}"></div><div class="setting"><span>Owner</span><input id="owner" type="text" value="${esc(state.project.owner)}"></div><div class="setting"><span>Accent</span><input id="accent" type="color" value="${esc(s.accent)}"></div><div class="setting"><span>Theme</span><select id="theme"><option value="midnight" ${s.theme==="midnight"?"selected":""}>Midnight</option><option value="dark" ${s.theme==="dark"?"selected":""}>Dark</option><option value="light" ${s.theme==="light"?"selected":""}>Light</option></select></div><div class="setting"><span>Wallpaper</span><select id="wallpaper"><option value="grid" ${s.wallpaper==="grid"?"selected":""}>grid</option><option value="dots" ${s.wallpaper==="dots"?"selected":""}>dots</option><option value="plain" ${s.wallpaper==="plain"?"selected":""}>plain</option></select></div><div class="setting"><span>Density</span><select id="density"><option value="comfortable" ${s.density==="comfortable"?"selected":""}>comfortable</option><option value="compact" ${s.density==="compact"?"selected":""}>compact</option></select></div><div class="setting"><span>Interface scale</span><select id="scale">${["90%","100%","110%"].map(x=>`<option ${s.scale===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="setting"><span>Animations</span><input id="animations" type="checkbox" ${s.animations?"checked":""}></div><div class="setting"><span>Autosave</span><input id="autosave" type="checkbox" ${s.autosave!==false?"checked":""}></div><div class="setting"><span>Startup page</span><select id="startup">${["home","projects","code","circuits","studio","world","memory","devices","pages"].map(x=>`<option ${s.startup===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="setting"><span>Sidebar width</span><select id="sidebar"><option value="210px" ${s.sidebar==="210px"?"selected":""}>210px</option><option value="230px" ${s.sidebar==="230px"?"selected":""}>230px</option><option value="260px" ${s.sidebar==="260px"?"selected":""}>260px</option></select></div><button class="primary" onclick="saveSettings()">Save Personalization</button><button onclick="persistNow(true)">Save Workspace Now</button><button onclick="exportWorkspace()">Export Full Workspace</button><button onclick="importWorkspace()">Import Full Workspace</button><button onclick="clearData()">Reset Local Data</button></div>
<div class="card"><h2>Storage</h2><p class="muted">FOX OS saves to this browser/PWA locally. Autosave writes changes after a brief pause and the Save button forces an immediate write.</p><div class="storage-row"><span>Storage key</span><code>${STORAGE_KEY}</code></div><div class="storage-row"><span>Last saved</span><span id="lastSavedText">${lastSavedAt?lastSavedAt.toLocaleString():"Session load completed"}</span></div></div></div>`}
function plugins(){return `<div class="grid"><div class="card"><h2>Plugin Slots</h2>${state.plugins.map(p=>`<div class="row"><span><b>${esc(p.name)}</b><br><small class="muted">${esc(p.source)}</small></span><button onclick="togglePlugin('${esc(p.id)}')">${p.enabled?"Enabled":"Disabled"}</button></div>`).join("")}<button onclick="addPlugin()">Add Plugin</button></div><div class="card"><h2>Extensibility</h2><p class="muted">Plugins can add modules without replacing the FOX OS core. External code is not executed by this companion automatically.</p></div></div>`}
function tasks(){return `<div class="grid"><div class="card"><h2>FOX Task Board</h2><input id="taskInput" type="text" placeholder="New task..."><button onclick="addTask()">Add Task</button></div><div class="card"><h2>Tasks</h2>${state.tasks.map(t=>`<div class="row"><label><input type="checkbox" ${t.done?"checked":""} onchange="toggleTask(${t.id})"> ${esc(t.title)}</label><button onclick="deleteTask(${t.id})">Delete</button></div>`).join("")}</div></div>`}

/* ---------- Custom pages ---------- */
function pageTemplates(){return [
  {key:"text",title:"Text",icon:"T",description:"A rich text section",defaults:{text:"Write something useful here…"}},
  {key:"note",title:"Note",icon:"✦",description:"Persistent editable note",defaults:{title:"Project Note",text:"Type a note. It stays saved with this page."}},
  {key:"stat",title:"Live Stat",icon:"#",description:"Live project number",defaults:{label:"Project files",source:"projectFiles"}},
  {key:"button",title:"Action Button",icon:"▶",description:"Button that runs a FOX action",defaults:{label:"Open Code",action:"code"}},
  {key:"link",title:"Link",icon:"↗",description:"Open a web link",defaults:{label:"FOX OSC GitHub",url:"https://github.com/foxbin8766-oss/FoxOSC"}},
  {key:"tasks",title:"Task Board",icon:"☑",description:"Your live task list",defaults:{}},
  {key:"memories",title:"Memory Feed",icon:"◫",description:"Recent memories and snapshots",defaults:{}},
  {key:"builds",title:"Build Feed",icon:"✓",description:"Recent validation runs",defaults:{}},
  {key:"files",title:"Project Files",icon:"▤",description:"Live project file list",defaults:{}},
  {key:"bookmarks",title:"Bookmarks",icon:"☆",description:"Saved browser links",defaults:{}},
  {key:"notifications",title:"Notifications",icon:"!",description:"Recent FOX OS notifications",defaults:{}},
  {key:"launcher",title:"Launcher",icon:"◆",description:"Quick-open another FOX OS module",defaults:{label:"Open Game Studio",target:"studio"}}
]}
function defaultPage(){return {id:"p"+Date.now()+Math.floor(Math.random()*10000),title:"My FOX Page",subtitle:"A page built by me",icon:"▣",tags:["custom"],columns:2,showInNav:true,blocks:[{id:"b"+Date.now(),type:"text",data:{text:"Welcome to my custom FOX OS page!"}},{id:"b"+(Date.now()+1),type:"stat",data:{label:"Project files",source:"projectFiles"}},{id:"b"+(Date.now()+2),type:"tasks",data:{}}]}}
function pagesManager(){return `<div class="grid"><div class="card"><div class="rowline"><h2>My Pages</h2><button class="primary" onclick="createPage()">+ New Page</button></div><p class="muted">Build pages out of real FOX OS blocks. Everything here is saved in your local workspace.</p>${state.pages.map((p,i)=>`<div class="row"><span><b>${esc(p.icon||"▣")} ${esc(p.title)}</b><br><small class="muted">${esc(p.subtitle||"")} • ${p.blocks?.length||0} blocks • ${p.showInNav===false?"hidden from nav":"pinned"}</small></span><span class="row-actions"><button onclick="go('page:${p.id}')">Open</button><button onclick="editPage(${i})">Edit</button><button onclick="duplicatePage(${i})">Copy</button><button onclick="deletePage(${i})">Delete</button></span></div>`).join("")||'<p class="muted">No pages yet. Create one to start adding content.</p>'}</div>
<div class="card"><h2>Page toolkit</h2>${pageTemplates().map(t=>`<div class="tool-row"><span><b>${t.icon} ${esc(t.title)}</b><small>${esc(t.description)}</small></span></div>`).join("")}<div class="toolbar"><button onclick="exportPages()">Export Pages</button><button onclick="importPages()">Import Pages</button></div></div></div>`}
function customPage(id){const p=state.pages.find(x=>x.id===id);if(!p){view="pages";return pagesManager()}return `<div class="page-shell"><div class="page-head"><div><div class="page-kicker">${esc((p.tags||[]).join(" • "))}</div><h1>${esc(p.icon||"▣")} ${esc(p.title)}</h1><p class="muted">${esc(p.subtitle||"")}</p></div><div class="toolbar"><button onclick="editPage(${state.pages.indexOf(p)})">Edit Page</button><button onclick="addBlockToPage('${esc(p.id)}')">+ Add Block</button><button onclick="duplicatePage(${state.pages.indexOf(p)})">Copy</button></div></div><div class="page-grid columns-${Math.min(3,Math.max(1,Number(p.columns)||2))}">${(p.blocks||[]).map((b,i)=>renderBlock(b,i,p)).join("")||'<div class="card"><p class="muted">This page is empty. Add a block to start building it.</p></div>'}</div></div>`}
function renderBlock(b,i,p){const d=b.data||{};const controls=`<div class="block-controls"><small>Block ${i+1}</small><button onclick="moveBlock('${p.id}',${i},-1)" ${i===0?"disabled":""}>↑</button><button onclick="moveBlock('${p.id}',${i},1)" ${i===p.blocks.length-1?"disabled":""}>↓</button><button onclick="editBlock('${p.id}',${i})">Edit</button><button onclick="deleteBlock('${p.id}',${i})">×</button></div>`;
  if(b.type==="text")return `<article class="card page-block text-block"><div class="block-head"><h2>${esc(d.title||"Text")}</h2>${controls}</div><p>${esc(d.text||"").replace(/\n/g,"<br>")}</p></article>`;
  if(b.type==="note")return `<article class="card page-block"><div class="block-head"><h2>${esc(d.title||"Note")}</h2>${controls}</div><textarea class="page-note" data-page="${esc(p.id)}" data-block="${i}">${esc(d.text||"")}</textarea></article>`;
  if(b.type==="stat"){let val=statValue(d.source);return `<article class="card page-block"><div class="block-head"><h2>${esc(d.label||"Stat")}</h2>${controls}</div><div class="stat">${esc(val)}</div><div class="statlabel">Live value</div></article>`}
  if(b.type==="button")return `<article class="card page-block"><div class="block-head"><h2>Action</h2>${controls}</div><button class="primary wide" onclick="pageAction('${esc(d.action||"home")}')">${esc(d.label||"Run Action")}</button></article>`;
  if(b.type==="link")return `<article class="card page-block"><div class="block-head"><h2>Link</h2>${controls}</div><button class="wide" onclick="openLink('${esc(d.url||"")}')">${esc(d.label||d.url||"Open Link")}</button><small class="muted">${esc(d.url||"")}</small></article>`;
  if(b.type==="tasks")return `<article class="card page-block"><div class="block-head"><h2>Tasks</h2>${controls}</div>${state.tasks.slice(0,6).map(t=>`<label class="check-row"><input type="checkbox" ${t.done?"checked":""} onchange="toggleTask(${t.id})"> ${esc(t.title)}</label>`).join("")||'<p class="muted">No tasks.</p>'}<button onclick="pageAction('tasks')">Open Task Board</button></article>`;
  if(b.type==="memories")return `<article class="card page-block"><div class="block-head"><h2>Memories</h2>${controls}</div>${state.memories.slice(0,5).map(m=>`<div class="mini-row"><span>${esc(m.text)}</span><small>${esc(m.time)}</small></div>`).join("")||'<p class="muted">No memories.</p>'}<button onclick="pageAction('memory')">Open Memory Core</button></article>`;
  if(b.type==="builds")return `<article class="card page-block"><div class="block-head"><h2>Builds</h2>${controls}</div>${state.builds.slice(-5).reverse().map(x=>`<div class="mini-row"><span>${esc(x.result)}</span><small>${esc(x.time)}</small></div>`).join("")||'<p class="muted">No builds yet.</p>'}<button onclick="pageAction('logs')">Open Logs</button></article>`;
  if(b.type==="files")return `<article class="card page-block"><div class="block-head"><h2>Project Files</h2>${controls}</div>${Object.keys(state.project.files).map(f=>`<div class="mini-row"><button class="linkish" onclick="sel('${esc(f)}')">${esc(f)}</button><small>${state.project.files[f].length} chars</small></div>`).join("")}<button onclick="pageAction('code')">Open Code</button></article>`;
  if(b.type==="bookmarks")return `<article class="card page-block"><div class="block-head"><h2>Bookmarks</h2>${controls}</div>${state.bookmarks.slice(0,6).map(u=>`<div class="mini-row"><button class="linkish" onclick="openLink('${esc(u)}')">${esc(u)}</button></div>`).join("")||'<p class="muted">No bookmarks yet.</p>'}</article>`;
  if(b.type==="notifications")return `<article class="card page-block"><div class="block-head"><h2>Notifications</h2>${controls}</div>${state.notifications.slice(0,6).map(n=>`<div class="mini-row"><span>${esc(n.msg)}</span><small>${esc(n.time)}</small></div>`).join("")||'<p class="muted">No notifications.</p>'}</article>`;
  if(b.type==="launcher")return `<article class="card page-block"><div class="block-head"><h2>Launcher</h2>${controls}</div><button class="primary wide" onclick="pageAction('${esc(d.target||"home")}')">${esc(d.label||"Open")}</button></article>`;
  return `<article class="card page-block"><div class="block-head"><h2>${esc(b.type)}</h2>${controls}</div><p class="muted">Unknown block type.</p></article>`;
}
function statValue(src){switch(src){case"projectFiles":return projectCount();case"builds":return state.builds.length;case"tasks":return state.tasks.filter(x=>!x.done).length;case"memories":return state.memories.length;case"pages":return state.pages.length;case"bookmarks":return state.bookmarks.length;case"plugins":return state.plugins.filter(x=>x.enabled).length;default:return "—"}}
function pageAction(action){if(action.startsWith("page:"))go(action);else go(action)}
function createPage(){const p=defaultPage();const n=prompt("Page name",p.title);if(!n)return;p.title=n;state.pages.push(p);save();render();go("page:"+p.id);notify("Custom page created")}
function editPage(i){const p=state.pages[i];if(!p)return;const title=prompt("Page title",p.title);if(title===null)return;p.title=title||"My FOX Page";const sub=prompt("Subtitle",p.subtitle||"");if(sub!==null)p.subtitle=sub;const icon=prompt("Icon",p.icon||"▣");if(icon!==null)p.icon=icon||"▣";const cols=Number(prompt("Columns (1, 2, or 3)",String(p.columns||2)));if([1,2,3].includes(cols))p.columns=cols;const tags=prompt("Tags (comma separated)",(p.tags||[]).join(", "));if(tags!==null)p.tags=tags.split(",").map(x=>x.trim()).filter(Boolean).slice(0,8);const pin=confirm("Show this page in the sidebar?\nOK = yes\nCancel = no");p.showInNav=pin;save();render();notify("Page settings saved")}
function duplicatePage(i){const p=state.pages[i];if(!p)return;const copy=clone(p);copy.id="p"+Date.now()+Math.floor(Math.random()*10000);copy.title=p.title+" Copy";copy.blocks=(copy.blocks||[]).map(b=>({...b,id:"b"+Date.now()+Math.floor(Math.random()*100000)}));state.pages.splice(i+1,0,copy);save();render();go("page:"+copy.id);notify("Page duplicated")}
function deletePage(i){const p=state.pages[i];if(!p)return;if(confirm("Delete page \""+p.title+"\"?")){state.pages.splice(i,1);save();render();go("pages");notify("Page deleted")}}
function addBlockToPage(id){const p=state.pages.find(x=>x.id===id);if(!p)return;const types=pageTemplates();const pick=prompt("Block type:\n"+types.map((x,i)=>`${i+1}. ${x.title}`).join("\n"),"1");const idx=Number(pick)-1;const t=types[idx];if(!t){toast("Choose a valid block");return}const b={id:"b"+Date.now()+Math.floor(Math.random()*10000),type:t.key,data:clone(t.defaults)};p.blocks=p.blocks||[];p.blocks.push(b);save();render();notify(t.title+" block added")}
function editBlock(pid,idx){const p=state.pages.find(x=>x.id===pid),b=p?.blocks?.[idx];if(!b)return;const d=b.data||{};if(b.type==="text"){const title=prompt("Block title",d.title||"Text");if(title!==null)d.title=title;const text=prompt("Text",d.text||"");if(text!==null)d.text=text}
else if(b.type==="note"){const title=prompt("Note title",d.title||"Project Note");if(title!==null)d.title=title}
else if(b.type==="stat"){const label=prompt("Label",d.label||"Live Stat");if(label!==null)d.label=label;const sources=["projectFiles","builds","tasks","memories","pages","bookmarks","plugins"];const src=prompt("Source:\n"+sources.join(" | "),d.source||"projectFiles");if(sources.includes(src))d.source=src}
else if(b.type==="button"){const label=prompt("Button label",d.label||"Open");if(label!==null)d.label=label;const action=prompt("Action (home, code, studio, world, memory, devices, tasks, pages)",d.action||"home");if(action!==null)d.action=action}
else if(b.type==="link"){const label=prompt("Link label",d.label||"Open Link");if(label!==null)d.label=label;const url=prompt("URL",d.url||"https://");if(url!==null)d.url=url}
else if(b.type==="launcher"){const label=prompt("Launcher label",d.label||"Open");if(label!==null)d.label=label;const target=prompt("Target page/module",d.target||"studio");if(target!==null)d.target=target}
b.data=d;save();render();notify("Block saved")}
function moveBlock(pid,idx,delta){const p=state.pages.find(x=>x.id===pid);if(!p)return;const to=idx+delta;if(to<0||to>=p.blocks.length)return;[p.blocks[idx],p.blocks[to]]=[p.blocks[to],p.blocks[idx]];save();render()}
function deleteBlock(pid,idx){const p=state.pages.find(x=>x.id===pid);if(!p||!confirm("Delete this block?"))return;p.blocks.splice(idx,1);save();render();notify("Block deleted")}
function exportPages(){download(JSON.stringify({version:"0.8",pages:state.pages},null,2),"foxos-pages.json","application/json");notify("Pages exported")}
function importPages(){const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),ps=Array.isArray(x.pages)?x.pages:null;if(!ps)throw 0;state.pages=[...state.pages,...ps.map(p=>({...p,id:p.id||"p"+Date.now()+Math.floor(Math.random()*10000),blocks:(p.blocks||[]).map(b=>({...b,id:b.id||"b"+Date.now()+Math.floor(Math.random()*10000)}))}))];save();render();notify("Pages imported")}catch{toast("Invalid FOX pages file")}};r.readAsText(f)};input.click()}
function openLink(u){if(/^https?:\/\//i.test(u))window.open(u,"_blank","noopener");else toast("Use an http:// or https:// link")}
function updateDynamicNav(){const old=document.getElementById("customNav");if(old)old.remove();const nav=document.getElementById("nav");const live=state.pages.filter(p=>p.showInNav!==false);if(!live.length)return;const wrap=document.createElement("div");wrap.id="customNav";wrap.className="custom-nav";live.forEach(p=>{const b=document.createElement("button");b.dataset.v="page:"+p.id;b.textContent=(p.icon||"▣")+" "+(p.title||"My Page");b.onclick=()=>go("page:"+p.id);b.className=(view==="page:"+p.id?"active":"");wrap.appendChild(b)});nav.after(wrap)}

/* ---------- Existing v0.7 behavior ---------- */
function bind(){
  if(view==="code"){const e=document.getElementById("ed");if(e)e.oninput=()=>{state.project.files[file]=e.value;save()}}
  if(view==="systems"){const s=document.getElementById("systemSearch");if(s)s.oninput=()=>document.querySelectorAll("#systemRows tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(s.value.toLowerCase())?"":"none")}
  if(view==="circuits")enableChips();
  if(view.startsWith("page:"))document.querySelectorAll(".page-note").forEach(e=>e.oninput=()=>{const p=state.pages.find(x=>x.id===e.dataset.page),b=p?.blocks?.[Number(e.dataset.block)];if(b){b.data.text=e.value;save()}});
}
function sel(x){file=x;flushSave();go("code")}
function newProject(){const n=prompt("Project name","My FOX OS Project");if(n){state.project={...clone(defaults),name:n,version:"0.8.0",files:{"Main.cs":"// FOX OS entry point\n"}};file="Main.cs";notify("Project created");go("code")}}
function renameProject(){const n=prompt("Project name",state.project.name);if(n){state.project.name=n;save();render()}}
function addFile(){const n=prompt("File name","App.cs");if(n&&!state.project.files[n]){state.project.files[n]="";file=n;save();render()}}
function deleteFile(){const fs=Object.keys(state.project.files);if(fs.length<=1){toast("Keep at least one file");return}if(confirm("Delete "+file+"?")){delete state.project.files[file];file=fs.find(x=>x!==file)||"Main.cs";save();render()}}
function duplicateProject(){state.project={...clone(state.project),name:state.project.name+" Copy"};save();notify("Project duplicated");render()}
function exportP(){download(JSON.stringify(state.project,null,2),(state.project.name||"foxos-project").replace(/[^a-z0-9_-]/gi,"_")+".json","application/json");notify("Project exported")}
function importP(){const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.files)throw 0;state.project={...clone(defaults),...p};file=Object.keys(state.project.files)[0];save();notify("Project imported");render()}catch{toast("Invalid FOX project file")}};r.readAsText(f)};input.click()}
function saveSettings(){state.profile.displayName=document.getElementById("profileName").value.trim()||"Foxbin";state.profile.subtitle=document.getElementById("profileSubtitle").value.trim()||"FOX OS Creator";state.project.owner=document.getElementById("owner").value||"Foxbin";state.settings.accent=document.getElementById("accent").value;state.settings.theme=document.getElementById("theme").value;state.settings.wallpaper=document.getElementById("wallpaper").value;state.settings.density=document.getElementById("density").value;state.settings.scale=document.getElementById("scale").value;state.settings.animations=document.getElementById("animations").checked;state.settings.autosave=document.getElementById("autosave").checked;state.settings.startup=document.getElementById("startup").value;state.settings.sidebar=document.getElementById("sidebar").value;applyTheme();persistNow(true);render()}
function applyTheme(){const s=state.settings||{};document.documentElement.dataset.theme=s.theme||"midnight";document.documentElement.dataset.wallpaper=s.wallpaper||"grid";document.documentElement.style.setProperty("--accent",s.accent||"#0796e6");document.documentElement.style.setProperty("--density",s.density==="compact"?"7px":"12px");document.documentElement.style.setProperty("--scale",s.scale||"100%");document.documentElement.style.setProperty("--sidebar",s.sidebar||"230px");document.body.classList.toggle("no-motion",s.animations===false)}
function clearData(){if(confirm("Reset all FOX OS companion data?")){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_KEY);location.reload()}}
function build(){go("logs");setTimeout(()=>{const lines=["> fox validate","✓ Project loaded","✓ Source files found","✓ BONELAB target selected","✓ FOX Core modules registered","✓ WristHub / BoneLib integration slots present","✓ Local validation passed","! DLL compilation remains a prototype connection layer","✓ Validation complete."];const box=document.getElementById("log");if(box)box.textContent=lines.join("\n")+"\n\n"+box.textContent;state.builds.push({time:new Date().toLocaleString(),result:"Validation complete"});state.history.push("Validation run");save();toast("Validation complete")},80)}
function snapshot(){const snap={time:new Date().toLocaleString(),project:clone(state.project),studio:clone(state.studio),world:clone(state.world),pages:clone(state.pages),circuits:clone(state.circuits)};state.memories.unshift({text:"Snapshot • "+snap.time,data:snap,time:snap.time});state.memories=state.memories.slice(0,25);notify("Snapshot created")}
function addMemory(){const e=document.getElementById("memText");if(e&&e.value.trim()){state.memories.unshift({text:e.value.trim(),time:new Date().toLocaleString()});e.value="";notify("Memory saved");render()}}
function deleteMemory(i){state.memories.splice(i,1);save();render()}
function exportWorkspace(){flushSave();download(JSON.stringify({format:"FOX OS Workspace",version:"0.8.0",savedAt:new Date().toISOString(),state},null,2),"foxos-workspace.json","application/json");notify("Workspace backup exported")}
function importWorkspace(){const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);const incoming=x.state||x;if(!incoming.project||!incoming.settings)throw 0;state=migrate(incoming);view=state.view||"home";file=state.file||Object.keys(state.project.files)[0];persistNow(false);render();notify("Full workspace restored")}catch{toast("Invalid FOX workspace backup")}};r.readAsText(f)};input.click()}
function download(text,name,type){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function addChip(kind){const c=document.getElementById("circuit");if(!c)return;state.circuits.nodes=state.circuits.nodes||[];const id="n"+Date.now()+Math.floor(Math.random()*10000);const x=Math.round(30+Math.random()*500),y=Math.round(30+Math.random()*300);state.circuits.nodes.push({id,kind,x,y});save();render();notify(kind+" chip added")}
function enableChips(){document.querySelectorAll(".chip[data-node]").forEach(enableChip)}
function enableChip(el){if(el.dataset.bound)return;el.dataset.bound="1";el.onpointerdown=e=>{e.preventDefault();const r=el.parentElement.getBoundingClientRect(),ox=e.clientX-el.offsetLeft,oy=e.clientY-el.offsetTop;el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{const x=Math.max(0,Math.min(r.width-el.offsetWidth,ev.clientX-r.left-ox));const y=Math.max(0,Math.min(r.height-el.offsetHeight,ev.clientY-r.top-oy));el.style.left=x+"px";el.style.top=y+"px"};el.onpointerup=()=>{const n=state.circuits.nodes.find(n=>n.id===el.dataset.node);if(n){n.x=parseInt(el.style.left,10)||0;n.y=parseInt(el.style.top,10)||0;save()}el.onpointermove=null}}}
function clearCircuit(){if(confirm("Reset the saved circuit canvas?")){state.circuits=clone(baseState.circuits);save();render();notify("Circuit reset")}}
function runCircuit(){state.circuits.runs=(state.circuits.runs||0)+1;state.history.push("Circuit run");save();notify("Circuit prototype executed")}
function simOpen(x){document.getElementById("simWindow").innerHTML=`<b>FOX OS ${esc(x)}</b><p class="muted">Virtual device preview. This is not a physical Quest connection.</p><button onclick="notify('${esc(x)} test action executed')">Test action</button>`}
function insertTemplate(type){const t={BoneLib:`using BoneLib;\n\npublic void Start() {\n    // FOX OS startup code\n}\n`,WristHub:`// WristHub app template\npublic void InitializeApp() {\n    // Connect app UI here\n}\n`,Event:`// BONELAB event handler\nvoid OnEvent() {\n    // Handle event\n}\n`};state.project.files[file]=(state.project.files[file]||"")+"\n"+t[type];save();go("code");notify(type+" template inserted")}
function nav(){let u=document.getElementById("url").value.trim();if(!/^https?:\/\//i.test(u))u="https://www.google.com/search?q="+encodeURIComponent(u);state.settings.lastUrl=u;document.getElementById("frame").src=u;document.getElementById("url").value=u;state.history.push("Browser: "+u);save()}
function reload(){const f=document.getElementById("frame");if(f)f.src=f.src}
function chrome(){const u=document.getElementById("url").value;window.open(u,"_blank","noopener")}
function bookmark(){const u=document.getElementById("url").value;if(u&&!state.bookmarks.includes(u)){state.bookmarks.push(u);save();notify("Bookmark saved")}else toast("Already bookmarked")}
function browserBack(){try{document.getElementById("frame").contentWindow.history.back()}catch{}}
function browserForward(){try{document.getElementById("frame").contentWindow.history.forward()}catch{}}
function pairQuest(){state.devices={quest:"virtual",status:"Connected (Virtual)"};notify("Virtual Quest paired");render()}
function disconnectQuest(){state.devices.status="Disconnected";notify("Device bridge disconnected");render()}
function sendTest(){if(state.devices.status.startsWith("Connected"))notify("Test packet sent to virtual Quest");else toast("Connect a device first")}
function toggleStudioMode(){state.studio.mode=state.studio.mode==="edit"?"play":"edit";save();render();notify("Studio mode: "+state.studio.mode)}
function addStudioObject(){const o=prompt("Object name","Interactable");if(o)addStudioObjectNamed(o)}
function addStudioObjectNamed(o){if(o){state.studio.objects.push(o);save();render();notify("Scene object added")}}
function removeStudioObject(i){state.studio.objects.splice(i,1);save();render()}
function clearStudio(){if(confirm("Clear scene objects?")){state.studio.objects=[];save();render()}}
function saveStudioScene(){state.history.push("Studio scene saved");persistNow(true);render()}
function saveWorld(){state.world.grid=document.getElementById("worldGrid").checked;state.world.day=Number(document.getElementById("worldDay").value);state.world.weather=document.getElementById("worldWeather").value;notify("World saved");render()}
function addWorldNode(){const n=prompt("Node name","Trigger");if(n){state.world.nodes.push(n);save();render()}}
function removeWorldNode(i){state.world.nodes.splice(i,1);save();render()}
function toggleAgent(id){const a=state.agents.find(x=>x.id===id);if(a){a.enabled=!a.enabled;save();render()}}
function addAgent(){const n=prompt("Agent name","New Agent");if(n){state.agents.push({id:"a"+Date.now(),name:n,role:"Custom project agent",status:"Ready",enabled:true});save();render()}}
function togglePlugin(id){const p=state.plugins.find(x=>x.id===id);if(p){p.enabled=!p.enabled;save();render();notify(p.name+" "+(p.enabled?"enabled":"disabled"))}}
function addPlugin(){const n=prompt("Plugin name","My Module");if(n){state.plugins.push({id:"p"+Date.now(),name:n,enabled:true,source:"local slot"});save();render();notify("Plugin slot created")}}
function addTask(){const e=document.getElementById("taskInput");if(e&&e.value.trim()){state.tasks.push({id:Date.now(),title:e.value.trim(),done:false});e.value="";save();render()}}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save();render()}}
function deleteTask(id){state.tasks=state.tasks.filter(x=>x.id!==id);save();render()}

/* ---------- Command palette ---------- */
function paletteOpen(){document.getElementById("palette").classList.remove("hidden");const i=document.getElementById("paletteInput");i.value="";paletteRender();i.focus()}
function commandList(){return [["Go Home","home"],["Projects","projects"],["Code","code"],["Circuits","circuits"],["Game Studio","studio"],["World Builder","world"],["Memory Core","memory"],["Device Bridge","devices"],["Permissions","permissions"],["Agents","agents"],["Plugins","plugins"],["Tasks","tasks"],["Simulator","sim"],["Systems","systems"],["Browser","browser"],["Build / Logs","logs"],["Docs","docs"],["Settings","settings"],["My Pages","pages"],["Create Custom Page","create-page"],["New Project","new"],["Backup Workspace","backup"],["Save Workspace","save"]];}
let pi=0;
function paletteRender(){const q=document.getElementById("paletteInput").value.toLowerCase();const list=commandList().filter(x=>x[0].toLowerCase().includes(q));pi=Math.max(0,Math.min(pi,Math.max(0,list.length-1)));document.getElementById("paletteResults").innerHTML=list.map((x,i)=>`<div class="palette-item ${i===pi?"active":""}" data-cmd="${esc(x[1])}">${esc(x[0])}</div>`).join("");document.querySelectorAll(".palette-item").forEach(e=>e.onclick=()=>runCommand(e.dataset.cmd))}
function runCommand(c){document.getElementById("palette").classList.add("hidden");if(c==="new")newProject();else if(c==="backup")exportWorkspace();else if(c==="save")persistNow(true);else if(c==="create-page")createPage();else go(c)}
document.getElementById("commandBtn").onclick=paletteOpen;document.getElementById("paletteInput").oninput=paletteRender;document.getElementById("palette").onclick=e=>{if(e.target.id==="palette")e.currentTarget.classList.add("hidden")};
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();paletteOpen()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();persistNow(true)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="b"){e.preventDefault();build()}if(e.key==="Escape")document.getElementById("palette").classList.add("hidden")});
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>go(b.dataset.v));document.getElementById("new").onclick=newProject;window.addEventListener("beforeunload",flushSave);
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;const b=document.getElementById("installBtn");if(b){b.hidden=false;b.onclick=async()=>{deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;b.hidden=true}}});
window.addEventListener("appinstalled",()=>toast("FOX OS installed"));
applyTheme();setSaveState("Loaded","idle");render();
